// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import UpdateMessageReducer from "../update_message_reducer";
import UpdateMessagePositionReducer from "../update_message_position_reducer";
import UpdatePositionReducer from "../update_position_reducer";

export type UpdateMessageParams = __Infer<typeof UpdateMessageReducer>;
export type UpdateMessagePositionParams = __Infer<typeof UpdateMessagePositionReducer>;
export type UpdatePositionParams = __Infer<typeof UpdatePositionReducer>;

