// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Cursor = __t.object("Cursor", {
  id: __t.identity(),
  x: __t.i32(),
  y: __t.i32(),
});
export type Cursor = __Infer<typeof Cursor>;

export const Message = __t.object("Message", {
  id: __t.u8(),
  message: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const MessagePosition = __t.object("MessagePosition", {
  id: __t.u8(),
  x: __t.i32(),
  y: __t.i32(),
});
export type MessagePosition = __Infer<typeof MessagePosition>;

